/** State-level base sales tax rates on vehicle purchases (%) */
export const STATE_TAX_RATES: Record<string, number> = {
  AL: 2.0,  AK: 0.0,  AZ: 5.6,  AR: 6.5,  CA: 7.25,
  CO: 2.9,  CT: 6.35, DE: 0.0,  FL: 6.0,  GA: 7.0,
  HI: 4.0,  ID: 6.0,  IL: 6.25, IN: 7.0,  IA: 5.0,
  KS: 6.5,  KY: 6.0,  LA: 4.45, ME: 5.5,  MD: 6.0,
  MA: 6.25, MI: 6.0,  MN: 6.875,MS: 5.0,  MO: 4.225,
  MT: 0.0,  NE: 5.5,  NV: 8.25, NH: 0.0,  NJ: 6.625,
  NM: 4.0,  NY: 4.0,  NC: 3.0,  ND: 5.0,  OH: 5.75,
  OK: 1.25, OR: 0.0,  PA: 6.0,  RI: 7.0,  SC: 5.0,
  SD: 4.5,  TN: 7.0,  TX: 6.25, UT: 6.85, VT: 6.0,
  VA: 4.15, WA: 6.5,  WV: 6.0,  WI: 5.0,  WY: 4.0,
  DC: 6.0,
};

export const US_STATES: { abbr: string; name: string }[] = [
  { abbr: "AL", name: "Alabama" },       { abbr: "AK", name: "Alaska" },
  { abbr: "AZ", name: "Arizona" },       { abbr: "AR", name: "Arkansas" },
  { abbr: "CA", name: "California" },    { abbr: "CO", name: "Colorado" },
  { abbr: "CT", name: "Connecticut" },   { abbr: "DE", name: "Delaware" },
  { abbr: "FL", name: "Florida" },       { abbr: "GA", name: "Georgia" },
  { abbr: "HI", name: "Hawaii" },        { abbr: "ID", name: "Idaho" },
  { abbr: "IL", name: "Illinois" },      { abbr: "IN", name: "Indiana" },
  { abbr: "IA", name: "Iowa" },          { abbr: "KS", name: "Kansas" },
  { abbr: "KY", name: "Kentucky" },      { abbr: "LA", name: "Louisiana" },
  { abbr: "ME", name: "Maine" },         { abbr: "MD", name: "Maryland" },
  { abbr: "MA", name: "Massachusetts" }, { abbr: "MI", name: "Michigan" },
  { abbr: "MN", name: "Minnesota" },     { abbr: "MS", name: "Mississippi" },
  { abbr: "MO", name: "Missouri" },      { abbr: "MT", name: "Montana" },
  { abbr: "NE", name: "Nebraska" },      { abbr: "NV", name: "Nevada" },
  { abbr: "NH", name: "New Hampshire" }, { abbr: "NJ", name: "New Jersey" },
  { abbr: "NM", name: "New Mexico" },    { abbr: "NY", name: "New York" },
  { abbr: "NC", name: "North Carolina" },{ abbr: "ND", name: "North Dakota" },
  { abbr: "OH", name: "Ohio" },          { abbr: "OK", name: "Oklahoma" },
  { abbr: "OR", name: "Oregon" },        { abbr: "PA", name: "Pennsylvania" },
  { abbr: "RI", name: "Rhode Island" },  { abbr: "SC", name: "South Carolina" },
  { abbr: "SD", name: "South Dakota" },  { abbr: "TN", name: "Tennessee" },
  { abbr: "TX", name: "Texas" },         { abbr: "UT", name: "Utah" },
  { abbr: "VT", name: "Vermont" },       { abbr: "VA", name: "Virginia" },
  { abbr: "WA", name: "Washington" },    { abbr: "WV", name: "West Virginia" },
  { abbr: "WI", name: "Wisconsin" },     { abbr: "WY", name: "Wyoming" },
  { abbr: "DC", name: "Washington D.C." },
];
