export interface VehicleModel {
  slug: string;
  displayName: string;
}

export interface VehicleMake {
  slug: string;
  displayName: string;
  models: VehicleModel[];
}

export const VEHICLE_MAKES: VehicleMake[] = [
  {
    slug: "acura", displayName: "Acura",
    models: [
      { slug: "integra", displayName: "Integra" },
      { slug: "mdx", displayName: "MDX" },
      { slug: "rdx", displayName: "RDX" },
      { slug: "tlx", displayName: "TLX" },
      { slug: "zdx", displayName: "ZDX" },
    ],
  },
  {
    slug: "alfa-romeo", displayName: "Alfa Romeo",
    models: [
      { slug: "giulia", displayName: "Giulia" },
      { slug: "stelvio", displayName: "Stelvio" },
      { slug: "tonale", displayName: "Tonale" },
    ],
  },
  {
    slug: "aston-martin", displayName: "Aston Martin",
    models: [
      { slug: "db12", displayName: "DB12" },
      { slug: "dbx", displayName: "DBX" },
      { slug: "vantage", displayName: "Vantage" },
    ],
  },
  {
    slug: "audi", displayName: "Audi",
    models: [
      { slug: "a3", displayName: "A3" },
      { slug: "a4", displayName: "A4" },
      { slug: "a4 allroad", displayName: "A4 allroad" },
      { slug: "a5 cabriolet", displayName: "A5 Cabriolet" },
      { slug: "a5 coupe", displayName: "A5 Coupe" },
      { slug: "a5 sportback", displayName: "A5 Sportback" },
      { slug: "a6", displayName: "A6" },
      { slug: "a6 allroad", displayName: "A6 allroad" },
      { slug: "a7 sportback", displayName: "A7 Sportback" },
      { slug: "a8", displayName: "A8" },
      { slug: "e-tron gt", displayName: "e-tron GT" },
      { slug: "q3", displayName: "Q3" },
      { slug: "q4 e-tron", displayName: "Q4 e-tron" },
      { slug: "q5", displayName: "Q5" },
      { slug: "q7", displayName: "Q7" },
      { slug: "q8", displayName: "Q8" },
      { slug: "q8 e-tron", displayName: "Q8 e-tron" },
      { slug: "rs 3 sedan", displayName: "RS 3 Sedan" },
      { slug: "rs 5 coupe", displayName: "RS 5 Coupe" },
      { slug: "rs 7 sportback", displayName: "RS 7 Sportback" },
      { slug: "s3", displayName: "S3" },
      { slug: "s4", displayName: "S4" },
      { slug: "s5 coupe", displayName: "S5 Coupe" },
      { slug: "sq5", displayName: "SQ5" },
      { slug: "sq7", displayName: "SQ7" },
      { slug: "sq8", displayName: "SQ8" },
    ],
  },
  {
    slug: "bentley", displayName: "Bentley",
    models: [
      { slug: "bentayga", displayName: "Bentayga" },
      { slug: "continental gt", displayName: "Continental GT" },
      { slug: "flying spur", displayName: "Flying Spur" },
    ],
  },
  {
    slug: "bmw", displayName: "BMW",
    models: [
      { slug: "2 series", displayName: "2 Series" },
      { slug: "3 series", displayName: "3 Series" },
      { slug: "4 series", displayName: "4 Series" },
      { slug: "5 series", displayName: "5 Series" },
      { slug: "7 series", displayName: "7 Series" },
      { slug: "8 series", displayName: "8 Series" },
      { slug: "i4", displayName: "i4" },
      { slug: "i5", displayName: "i5" },
      { slug: "i7", displayName: "i7" },
      { slug: "ix", displayName: "iX" },
      { slug: "m2", displayName: "M2" },
      { slug: "m3", displayName: "M3" },
      { slug: "m4", displayName: "M4" },
      { slug: "m5", displayName: "M5" },
      { slug: "x1", displayName: "X1" },
      { slug: "x2", displayName: "X2" },
      { slug: "x3", displayName: "X3" },
      { slug: "x4", displayName: "X4" },
      { slug: "x5", displayName: "X5" },
      { slug: "x6", displayName: "X6" },
      { slug: "x7", displayName: "X7" },
      { slug: "z4", displayName: "Z4" },
    ],
  },
  {
    slug: "buick", displayName: "Buick",
    models: [
      { slug: "enclave", displayName: "Enclave" },
      { slug: "encore gx", displayName: "Encore GX" },
      { slug: "envision", displayName: "Envision" },
      { slug: "envista", displayName: "Envista" },
    ],
  },
  {
    slug: "cadillac", displayName: "Cadillac",
    models: [
      { slug: "ct4", displayName: "CT4" },
      { slug: "ct5", displayName: "CT5" },
      { slug: "escalade", displayName: "Escalade" },
      { slug: "escalade esv", displayName: "Escalade ESV" },
      { slug: "lyriq", displayName: "LYRIQ" },
      { slug: "optiq", displayName: "OPTIQ" },
      { slug: "xt4", displayName: "XT4" },
      { slug: "xt5", displayName: "XT5" },
      { slug: "xt6", displayName: "XT6" },
    ],
  },
  {
    slug: "chevrolet", displayName: "Chevrolet",
    models: [
      { slug: "blazer", displayName: "Blazer" },
      { slug: "blazer ev", displayName: "Blazer EV" },
      { slug: "camaro", displayName: "Camaro" },
      { slug: "colorado", displayName: "Colorado" },
      { slug: "corvette", displayName: "Corvette" },
      { slug: "equinox", displayName: "Equinox" },
      { slug: "equinox ev", displayName: "Equinox EV" },
      { slug: "malibu", displayName: "Malibu" },
      { slug: "silverado 1500", displayName: "Silverado 1500" },
      { slug: "silverado 2500hd", displayName: "Silverado 2500HD" },
      { slug: "silverado 3500hd", displayName: "Silverado 3500HD" },
      { slug: "suburban", displayName: "Suburban" },
      { slug: "tahoe", displayName: "Tahoe" },
      { slug: "trailblazer", displayName: "Trailblazer" },
      { slug: "traverse", displayName: "Traverse" },
      { slug: "trax", displayName: "Trax" },
    ],
  },
  {
    slug: "chrysler", displayName: "Chrysler",
    models: [
      { slug: "pacifica", displayName: "Pacifica" },
      { slug: "voyager", displayName: "Voyager" },
    ],
  },
  {
    slug: "dodge", displayName: "Dodge",
    models: [
      { slug: "durango", displayName: "Durango" },
      { slug: "hornet", displayName: "Hornet" },
    ],
  },
  {
    slug: "fiat", displayName: "FIAT",
    models: [
      { slug: "500e", displayName: "500e" },
    ],
  },
  {
    slug: "ford", displayName: "Ford",
    models: [
      { slug: "bronco", displayName: "Bronco" },
      { slug: "bronco sport", displayName: "Bronco Sport" },
      { slug: "edge", displayName: "Edge" },
      { slug: "escape", displayName: "Escape" },
      { slug: "expedition", displayName: "Expedition" },
      { slug: "expedition max", displayName: "Expedition Max" },
      { slug: "explorer", displayName: "Explorer" },
      { slug: "f-150", displayName: "F-150" },
      { slug: "f-150 lightning", displayName: "F-150 Lightning" },
      { slug: "f-250", displayName: "F-250" },
      { slug: "f-350", displayName: "F-350" },
      { slug: "maverick", displayName: "Maverick" },
      { slug: "mustang", displayName: "Mustang" },
      { slug: "mustang mach-e", displayName: "Mustang Mach-E" },
      { slug: "ranger", displayName: "Ranger" },
    ],
  },
  {
    slug: "genesis", displayName: "Genesis",
    models: [
      { slug: "g70", displayName: "G70" },
      { slug: "g80", displayName: "G80" },
      { slug: "g90", displayName: "G90" },
      { slug: "gv60", displayName: "GV60" },
      { slug: "gv70", displayName: "GV70" },
      { slug: "gv80", displayName: "GV80" },
    ],
  },
  {
    slug: "gmc", displayName: "GMC",
    models: [
      { slug: "acadia", displayName: "Acadia" },
      { slug: "canyon", displayName: "Canyon" },
      { slug: "hummer ev", displayName: "HUMMER EV" },
      { slug: "sierra 1500", displayName: "Sierra 1500" },
      { slug: "sierra 2500hd", displayName: "Sierra 2500HD" },
      { slug: "sierra 3500hd", displayName: "Sierra 3500HD" },
      { slug: "terrain", displayName: "Terrain" },
      { slug: "yukon", displayName: "Yukon" },
      { slug: "yukon xl", displayName: "Yukon XL" },
    ],
  },
  {
    slug: "honda", displayName: "Honda",
    models: [
      { slug: "accord", displayName: "Accord" },
      { slug: "civic", displayName: "Civic" },
      { slug: "civic hatchback", displayName: "Civic Hatchback" },
      { slug: "civic si", displayName: "Civic Si" },
      { slug: "cr-v", displayName: "CR-V" },
      { slug: "hr-v", displayName: "HR-V" },
      { slug: "odyssey", displayName: "Odyssey" },
      { slug: "passport", displayName: "Passport" },
      { slug: "pilot", displayName: "Pilot" },
      { slug: "prologue", displayName: "Prologue" },
      { slug: "ridgeline", displayName: "Ridgeline" },
    ],
  },
  {
    slug: "hyundai", displayName: "Hyundai",
    models: [
      { slug: "elantra", displayName: "Elantra" },
      { slug: "ioniq 5", displayName: "IONIQ 5" },
      { slug: "ioniq 6", displayName: "IONIQ 6" },
      { slug: "kona", displayName: "Kona" },
      { slug: "kona electric", displayName: "Kona Electric" },
      { slug: "palisade", displayName: "Palisade" },
      { slug: "santa cruz", displayName: "Santa Cruz" },
      { slug: "santa fe", displayName: "Santa Fe" },
      { slug: "sonata", displayName: "Sonata" },
      { slug: "tucson", displayName: "Tucson" },
      { slug: "venue", displayName: "Venue" },
    ],
  },
  {
    slug: "infiniti", displayName: "INFINITI",
    models: [
      { slug: "qx50", displayName: "QX50" },
      { slug: "qx55", displayName: "QX55" },
      { slug: "qx60", displayName: "QX60" },
      { slug: "qx80", displayName: "QX80" },
    ],
  },
  {
    slug: "jaguar", displayName: "Jaguar",
    models: [
      { slug: "e-pace", displayName: "E-PACE" },
      { slug: "f-pace", displayName: "F-PACE" },
      { slug: "f-type", displayName: "F-TYPE" },
      { slug: "i-pace", displayName: "I-PACE" },
      { slug: "xf", displayName: "XF" },
    ],
  },
  {
    slug: "jeep", displayName: "Jeep",
    models: [
      { slug: "compass", displayName: "Compass" },
      { slug: "gladiator", displayName: "Gladiator" },
      { slug: "grand cherokee", displayName: "Grand Cherokee" },
      { slug: "grand cherokee l", displayName: "Grand Cherokee L" },
      { slug: "grand wagoneer", displayName: "Grand Wagoneer" },
      { slug: "wagoneer", displayName: "Wagoneer" },
      { slug: "wrangler", displayName: "Wrangler" },
      { slug: "wrangler 4xe", displayName: "Wrangler 4xe" },
    ],
  },
  {
    slug: "kia", displayName: "Kia",
    models: [
      { slug: "carnival", displayName: "Carnival" },
      { slug: "ev6", displayName: "EV6" },
      { slug: "ev9", displayName: "EV9" },
      { slug: "forte", displayName: "Forte" },
      { slug: "k5", displayName: "K5" },
      { slug: "niro", displayName: "Niro" },
      { slug: "seltos", displayName: "Seltos" },
      { slug: "sorento", displayName: "Sorento" },
      { slug: "soul", displayName: "Soul" },
      { slug: "sportage", displayName: "Sportage" },
      { slug: "telluride", displayName: "Telluride" },
    ],
  },
  {
    slug: "land rover", displayName: "Land Rover",
    models: [
      { slug: "defender", displayName: "Defender" },
      { slug: "discovery", displayName: "Discovery" },
      { slug: "discovery sport", displayName: "Discovery Sport" },
      { slug: "range rover", displayName: "Range Rover" },
      { slug: "range rover evoque", displayName: "Range Rover Evoque" },
      { slug: "range rover sport", displayName: "Range Rover Sport" },
      { slug: "range rover velar", displayName: "Range Rover Velar" },
    ],
  },
  {
    slug: "lexus", displayName: "Lexus",
    models: [
      { slug: "es 250", displayName: "ES 250" },
      { slug: "es 300h", displayName: "ES 300h" },
      { slug: "es 350", displayName: "ES 350" },
      { slug: "gx 550", displayName: "GX 550" },
      { slug: "is 300", displayName: "IS 300" },
      { slug: "is 350", displayName: "IS 350" },
      { slug: "is 500", displayName: "IS 500" },
      { slug: "lc 500", displayName: "LC 500" },
      { slug: "ls 500", displayName: "LS 500" },
      { slug: "lx 600", displayName: "LX 600" },
      { slug: "nx 250", displayName: "NX 250" },
      { slug: "nx 350", displayName: "NX 350" },
      { slug: "nx 350h", displayName: "NX 350h" },
      { slug: "rc 300", displayName: "RC 300" },
      { slug: "rc 350", displayName: "RC 350" },
      { slug: "rx 350", displayName: "RX 350" },
      { slug: "rx 350h", displayName: "RX 350h" },
      { slug: "rx 500h", displayName: "RX 500h" },
      { slug: "rz", displayName: "RZ" },
      { slug: "tx 350", displayName: "TX 350" },
      { slug: "tx 500h", displayName: "TX 500h" },
      { slug: "ux 250h", displayName: "UX 250h" },
    ],
  },
  {
    slug: "lincoln", displayName: "Lincoln",
    models: [
      { slug: "aviator", displayName: "Aviator" },
      { slug: "corsair", displayName: "Corsair" },
      { slug: "nautilus", displayName: "Nautilus" },
      { slug: "navigator", displayName: "Navigator" },
    ],
  },
  {
    slug: "maserati", displayName: "Maserati",
    models: [
      { slug: "ghibli", displayName: "Ghibli" },
      { slug: "grancabrio", displayName: "GranCabrio" },
      { slug: "granturismo", displayName: "GranTurismo" },
      { slug: "grecale", displayName: "Grecale" },
      { slug: "levante", displayName: "Levante" },
      { slug: "mc20", displayName: "MC20" },
      { slug: "quattroporte", displayName: "Quattroporte" },
    ],
  },
  {
    slug: "mazda", displayName: "Mazda",
    models: [
      { slug: "cx-30", displayName: "CX-30" },
      { slug: "cx-5", displayName: "CX-5" },
      { slug: "cx-50", displayName: "CX-50" },
      { slug: "cx-70", displayName: "CX-70" },
      { slug: "cx-90", displayName: "CX-90" },
      { slug: "mazda3", displayName: "Mazda3" },
      { slug: "mazda3 hatchback", displayName: "Mazda3 Hatchback" },
    ],
  },
  {
    slug: "mercedes-benz", displayName: "Mercedes-Benz",
    models: [
      { slug: "amg gt", displayName: "AMG GT" },
      { slug: "cla 250", displayName: "CLA 250" },
      { slug: "cle 300", displayName: "CLE 300" },
      { slug: "cle 450", displayName: "CLE 450" },
      { slug: "e 350", displayName: "E 350" },
      { slug: "e 450", displayName: "E 450" },
      { slug: "eqb 250", displayName: "EQB 250" },
      { slug: "eqe 350", displayName: "EQE 350" },
      { slug: "eqs 450", displayName: "EQS 450" },
      { slug: "g 550", displayName: "G 550" },
      { slug: "gla 250", displayName: "GLA 250" },
      { slug: "glb 250", displayName: "GLB 250" },
      { slug: "glc 300", displayName: "GLC 300" },
      { slug: "gle 350", displayName: "GLE 350" },
      { slug: "gle 450", displayName: "GLE 450" },
      { slug: "gls 450", displayName: "GLS 450" },
      { slug: "s 500", displayName: "S 500" },
      { slug: "s 580", displayName: "S 580" },
      { slug: "sprinter 2500", displayName: "Sprinter 2500" },
    ],
  },
  {
    slug: "mini", displayName: "MINI",
    models: [
      { slug: "convertible", displayName: "Convertible" },
      { slug: "countryman", displayName: "Countryman" },
      { slug: "hardtop", displayName: "Hardtop" },
    ],
  },
  {
    slug: "mitsubishi", displayName: "Mitsubishi",
    models: [
      { slug: "eclipse cross", displayName: "Eclipse Cross" },
      { slug: "mirage", displayName: "Mirage" },
      { slug: "outlander", displayName: "Outlander" },
      { slug: "outlander sport", displayName: "Outlander Sport" },
    ],
  },
  {
    slug: "nissan", displayName: "Nissan",
    models: [
      { slug: "altima", displayName: "Altima" },
      { slug: "ariya", displayName: "ARIYA" },
      { slug: "armada", displayName: "Armada" },
      { slug: "frontier", displayName: "Frontier" },
      { slug: "kicks", displayName: "Kicks" },
      { slug: "leaf", displayName: "LEAF" },
      { slug: "murano", displayName: "Murano" },
      { slug: "pathfinder", displayName: "Pathfinder" },
      { slug: "rogue", displayName: "Rogue" },
      { slug: "sentra", displayName: "Sentra" },
      { slug: "titan", displayName: "TITAN" },
      { slug: "versa", displayName: "Versa" },
      { slug: "z", displayName: "Z" },
    ],
  },
  {
    slug: "ram", displayName: "RAM",
    models: [
      { slug: "1500", displayName: "1500" },
      { slug: "2500", displayName: "2500" },
      { slug: "3500", displayName: "3500" },
      { slug: "promaster 1500", displayName: "ProMaster 1500" },
      { slug: "promaster 2500", displayName: "ProMaster 2500" },
      { slug: "promaster 3500", displayName: "ProMaster 3500" },
    ],
  },
  {
    slug: "subaru", displayName: "Subaru",
    models: [
      { slug: "ascent", displayName: "Ascent" },
      { slug: "brz", displayName: "BRZ" },
      { slug: "crosstrek", displayName: "Crosstrek" },
      { slug: "forester", displayName: "Forester" },
      { slug: "impreza", displayName: "Impreza" },
      { slug: "legacy", displayName: "Legacy" },
      { slug: "outback", displayName: "Outback" },
      { slug: "solterra", displayName: "Solterra" },
      { slug: "wrx", displayName: "WRX" },
    ],
  },
  {
    slug: "tesla", displayName: "Tesla",
    models: [
      { slug: "cybertruck", displayName: "Cybertruck" },
      { slug: "model 3", displayName: "Model 3" },
      { slug: "model s", displayName: "Model S" },
      { slug: "model x", displayName: "Model X" },
      { slug: "model y", displayName: "Model Y" },
    ],
  },
  {
    slug: "toyota", displayName: "Toyota",
    models: [
      { slug: "4runner", displayName: "4Runner" },
      { slug: "bz4x", displayName: "bZ4X" },
      { slug: "camry", displayName: "Camry" },
      { slug: "corolla", displayName: "Corolla" },
      { slug: "corolla cross", displayName: "Corolla Cross" },
      { slug: "corolla hatchback", displayName: "Corolla Hatchback" },
      { slug: "crown", displayName: "Crown" },
      { slug: "gr86", displayName: "GR86" },
      { slug: "highlander", displayName: "Highlander" },
      { slug: "land cruiser", displayName: "Land Cruiser" },
      { slug: "prius", displayName: "Prius" },
      { slug: "prius prime", displayName: "Prius Prime" },
      { slug: "rav4", displayName: "RAV4" },
      { slug: "rav4 prime", displayName: "RAV4 Prime" },
      { slug: "sequoia", displayName: "Sequoia" },
      { slug: "sienna", displayName: "Sienna" },
      { slug: "tacoma", displayName: "Tacoma" },
      { slug: "tundra", displayName: "Tundra" },
      { slug: "venza", displayName: "Venza" },
    ],
  },
  {
    slug: "volkswagen", displayName: "Volkswagen",
    models: [
      { slug: "atlas", displayName: "Atlas" },
      { slug: "atlas cross sport", displayName: "Atlas Cross Sport" },
      { slug: "golf", displayName: "Golf" },
      { slug: "id.4", displayName: "ID.4" },
      { slug: "id.buzz", displayName: "ID. Buzz" },
      { slug: "jetta", displayName: "Jetta" },
      { slug: "taos", displayName: "Taos" },
      { slug: "tiguan", displayName: "Tiguan" },
    ],
  },
  {
    slug: "volvo", displayName: "Volvo",
    models: [
      { slug: "c40 recharge", displayName: "C40 Recharge" },
      { slug: "ex30", displayName: "EX30" },
      { slug: "ex90", displayName: "EX90" },
      { slug: "s60", displayName: "S60" },
      { slug: "s90", displayName: "S90" },
      { slug: "v60 cross country", displayName: "V60 Cross Country" },
      { slug: "xc40", displayName: "XC40" },
      { slug: "xc40 recharge", displayName: "XC40 Recharge" },
      { slug: "xc60", displayName: "XC60" },
      { slug: "xc90", displayName: "XC90" },
    ],
  },
];

export const MAKE_MAP = new Map(VEHICLE_MAKES.map((m) => [m.slug, m]));

const CURRENT_YEAR = new Date().getFullYear();
export const MODEL_YEARS = Array.from({ length: 6 }, (_, i) => CURRENT_YEAR - i);
